main/urls.py
from django.urls import path

from main.views import (
    IndexListView, ProductView, ProductsListView, CategoryListView, CategoryDetailView, LogInView, LogOutView,
    RegisterView, CartView, FavView
)


def index(request): pass


app_name = 'main'
urlpatterns = [
    # Index
    path('', IndexListView.as_view(), name='index'),

    # Products
    path('products/', ProductsListView.as_view(), name='products'),
    path('products/<slug:slug>/', ProductView.as_view(), name='view'),

    # Categories
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category-view'),

    # Brands
    path('brands/', index, name='brands'),
    path('brands/<slug:slug>/', index, name='brand-view'),

    # Country
    path('countries/', index, name='countries'),
    path('countries//<slug:slug>/', index, name='country-view'),

    # Auth
    path('login/', LogInView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogOutView.as_view(), name='logout'),

    # Account
    path('cart/', CartView.as_view(), name='cart'),
    path('favourites/', FavView.as_view(), name='favourites'),
    path('settings/', index, name='settings'),
]

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import Model, SlugField, CharField, ImageField, ForeignKey, SET, JSONField, TextField, FloatField, \
    IntegerField, DateTimeField, CASCADE


class User(AbstractUser):
    phone_number = CharField(max_length=20, null=True, blank=True)


class Category(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    icon = ImageField(upload_to='icons/category')

    def __str__(self):
        return f'{self.name}'


class Brand(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    icon = ImageField(upload_to='icons/brand')

    def __str__(self):
        return f'{self.name}'


class Country(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    flag = ImageField(upload_to='icons/flag')

    def __str__(self):
        return f'{self.name}'


class Product(Model):
    slug = SlugField(max_length=250)
    title = CharField(max_length=100)
    category = ForeignKey(Category, SET('Unknown'))
    brand = ForeignKey(Brand, SET('Unknown'))
    model = CharField(max_length=150)
    made = ForeignKey(Country, SET('Unknown'))
    details = JSONField(null=True, blank=True)
    description = TextField(null=True, blank=True)
    price = FloatField()
    discount = IntegerField(default=0)
    count = IntegerField(default=1)
    pub_date = DateTimeField(auto_now=True)
    edit_date = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'


class ProductImage(Model):
    product = ForeignKey(Product, CASCADE)
    image = ImageField(upload_to='products')

    def __str__(self):
        return f'{self.product}'


class Review(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, SET('Deleted'))
    text = CharField(max_length=200)
    date = DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.product} {self.user}'


class Favourite(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, CASCADE)

    def __str__(self):
        return f'{self.product}'


class Cart(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, CASCADE)
    count = IntegerField(default=1)

    class Meta:
        ordering = ('count',)

    def __str__(self):
        return f'{self.product}'

templates/products/cart.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
    {% for product in cart %}
        {{ product.product.title }}
        {{ product.product.brand }}
        {{ product.product.count }}
        {{ product.product.description }}
    {% empty %}
        Korzinada hozircha tovarar yo'q.
    {% endfor %}
{% endblock %}

templates/products/fav.html
{% extends 'base.html' %}

{% block title %}Favourites{% endblock %}

{% block content %}
    {% for product in favourites %}
        {{ product.product.title }}
        {{ product.product.brand }}
        {{ product.product.count }}
        {{ product.product.description }}
    {% empty %}
        Sevimlilaringizda hozircha tovarar yo'q.
    {% endfor %}
{% endblock %}

templates/products/list.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
    <section class="categories p-5 m-auto">
        <h3 class="text-center">Kategoriyalar</h3>
        <div class="text-center">
            {% for category in categories %}
                <a href="{% url 'main:category-view' category.slug %}"
                   class="btn btn-light shadow m-2" style="width: 150px">
                    <img src="{{ category.icon.url }}" alt="{{ category.slug }}"
                         width="40px" height="40px" class="rounded">
                    <h6>{{ category.name }}</h6>
                </a>
            {% empty %}
                <h4 class="text-center">Afsuski, bizda hozir kategoriyalar yo'q :.(</h4>
            {% endfor %}
        </div>
    </section>
    <hr>
    {% if products %}
        <section class="cards p-5">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow h-100">
                            <a href="{% url 'main:view' product.slug %}" class="text-decoration-none">
                                <img src="{{ product.productimage_set.first.image.url }}"
                                     class="card-img-top" alt="{{ product.title }}" width="100%" height="100%">
                            </a>
                            <div class="card-body">
                                <a href="{% url 'main:view' product.slug %}" class="text-decoration-none">
                                    <h5 class="card-title text-dark">{{ product.title }}</h5>
                                </a>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Brand:</span>
                                    <span class="w-50">{{ product.brand }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Model:</span>
                                    <span class="w-50">{{ product.model }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Ishlab chiqarilgan:</span>
                                    <span class="w-50">{{ product.made }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Qolgan:</span>
                                    <span class="w-50">{{ product.count }} ta</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Narxi:</span>
                                    <span class="w-50">{{ product.price }} so'm</span>
                                </div>
                            </div>
                            <div class="card-footer d-flex align-items-center justify-content-between">
                                <span class="text-muted">
                                    <i class="fa-solid fa-calendar-days mx-2"></i>
                                    {{ product.pub_date|timesince }}
                                </span>
                                <a class="text-muted text-decoration-none"
                                   href="{% url 'main:category-view' product.category.slug %}">
                                    <i class="fa-solid fa-tags mx-2"></i>{{ product.category }}
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    {% else %}
        <h1 class="text-center my-5">Bizda hali tovarlar yo'q ...(</h1>
    {% endif %}
{% endblock %}

templates/products/view.html
{% extends 'base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
    <div class="card my-3">
        <div class="row g-0">
            <div class="col-md-5">
                <div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for img in product.productimage_set.all %}
                            <div class="carousel-item{% if img == product.productimage_set.first %} active{% endif %}"
                                 data-bs-interval="5000">
                                <img src="{{ img.image.url }}" class="d-block w-100 h-100" alt="{{ product.title }}">
                            </div>
                        {% endfor %}

                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    <h5 class="card-title">{{ product.title }}</h5>
                    <hr style="margin-top: 5px; margin-bottom: 5px">
                    <div class="card-text d-flex w-100">
                        <span class="w-50">Brand:</span>
                        <a href="{% url 'main:brand-view' product.brand.slug %}"
                           class="text-decoration-none text-dark w-50">
                            {{ product.brand }}
                        </a>
                    </div>
                    <hr style="margin-top: 5px; margin-bottom: 5px">
                    <div class="card-text d-flex w-100">
                        <span class="w-50">Model:</span>
                        <span class="w-50">{{ product.model }}</span>
                    </div>
                    <hr style="margin-top: 5px; margin-bottom: 5px">
                    <div class="card-text d-flex w-100">
                        <span class="w-50">Ishlab chiqarilgan:</span>
                        <a href="{% url 'main:country-view' product.made.slug %}"
                           class="text-decoration-none text-dark w-50">
                            {{ product.made }}
                        </a>
                    </div>
                    <hr style="margin-top: 5px; margin-bottom: 5px">
                    <div class="card-text d-flex w-100">
                        <span class="w-50">Qolgan:</span>
                        <span class="w-50">{{ product.count }} ta</span>
                    </div>
                    <hr style="margin-top: 5px; margin-bottom: 5px">
                    <div class="card-text d-flex w-100">
                        <span class="w-50">Narxi:</span>
                        <span class="w-50">{{ product.price }} so'm</span>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="container px-5 py-3">
            {% if product.details %}
                <h2 class="text-center">Qo'shimcha ma'lumotlar</h2>
                <ul class="list">
                    {% for key, value in product.details.items %}
                        <li class="list-item">{{ key }}: {{ value }}</li>
                    {% endfor %}
                </ul>
                <hr>
            {% endif %}
            {% if product.description %}
                <p>{{ product.description|urlize }}</p>
                <hr>
            {% endif %}
            <div class="d-flex align-items-center justify-content-between">
                <div class="text-muted">
                    <p class="m-0 p-0">{{ product.pub_date|date:"d-M, H:i" }}</p>
                </div>
                <div class="d-flex">
                    <form action="{% url 'main:favourites' %}" method="post" class="form">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button type="submit" class="btn btn-sm btn-outline-danger px-2 m-1">
                            <i class="fa-solid fa-heart"></i> {{ product.favourite_set.count }}
                        </button>
                    </form>
                    <form action="{% url 'main:cart' %}" method="post" class="form">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <input type="hidden" name="product_count" value="1">
                        <button type="submit" class="btn btn-sm btn-outline-success px-3 m-1">
                            <i class="fa-solid fa-cart-arrow-down"></i>
                            {#<i class="fa-solid fa-cart-shopping"></i> <i class="fa-solid fa-check"></i>#}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <section class="comment">
        <div class="row d-flex justify-content-center">
            <div class="col-md-8 col-lg-6">
                <div class="card shadow-0 border" style="background-color: #f0f2f5;">
                    <div class="card-body p-4">
                        <form class="form-outline mb-4 d-flex align-items-center" method="post">
                            {% csrf_token %}
                            <input type="text" class="form-control mx-1" placeholder="Izoh qoldirish" name="text"
                                   maxlength="200" minlength="5" required>
                            <button type="submit" class="btn btn-outline-success mx-1"><i
                                    class="fa-regular fa-share-from-square"></i></button>
                        </form>
                        {% for review in reviews %}
                            <div class="card my-3">
                                <div class="card-body">
                                    <p>{{ review.text }}</p>

                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center">
                                            <i class="fa-regular fa-user mx-2"></i>
                                            <p class="small mb-0 ms-2">{{ review.user }}</p>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <p class="small text-muted mb-0">{{ review.date|timesince }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}