main/urls.py
from django.urls import path

from main.views import (
    IndexListView, ProductView, ProductsListView, CategoryListView, CategoryDetailView, LogInView, LogOutView,
    RegisterView, CartView, FavView
)


def index(request): pass


app_name = 'main'
urlpatterns = [
    # Index
    path('', IndexListView.as_view(), name='index'),

    # Products
    path('products/', ProductsListView.as_view(), name='products'),
    path('products/<slug:slug>/', ProductView.as_view(), name='view'),

    # Categories
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category-view'),

    # Brands
    path('brands/', index, name='brands'),
    path('brands/<slug:slug>/', index, name='brand-view'),

    # Country
    path('countries/', index, name='countries'),
    path('countries//<slug:slug>/', index, name='country-view'),

    # Auth
    path('login/', LogInView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogOutView.as_view(), name='logout'),

    # Account
    path('cart/', CartView.as_view(), name='cart'),
    path('favourites/', FavView.as_view(), name='favourites'),
    path('settings/', index, name='settings'),
]

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import Model, SlugField, CharField, ImageField, ForeignKey, SET, JSONField, TextField, FloatField, \
    IntegerField, DateTimeField, CASCADE


class User(AbstractUser):
    phone_number = CharField(max_length=20, null=True, blank=True)


class Category(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    icon = ImageField(upload_to='icons/category')

    def __str__(self):
        return f'{self.name}'


class Brand(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    icon = ImageField(upload_to='icons/brand')

    def __str__(self):
        return f'{self.name}'


class Country(Model):
    slug = SlugField(max_length=100)
    name = CharField(max_length=100)
    flag = ImageField(upload_to='icons/flag')

    def __str__(self):
        return f'{self.name}'


class Product(Model):
    slug = SlugField(max_length=250)
    title = CharField(max_length=100)
    category = ForeignKey(Category, SET('Unknown'))
    brand = ForeignKey(Brand, SET('Unknown'))
    model = CharField(max_length=150)
    made = ForeignKey(Country, SET('Unknown'))
    details = JSONField(null=True, blank=True)
    description = TextField(null=True, blank=True)
    price = FloatField()
    discount = IntegerField(default=0)
    count = IntegerField(default=1)
    pub_date = DateTimeField(auto_now=True)
    edit_date = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'


class ProductImage(Model):
    product = ForeignKey(Product, CASCADE)
    image = ImageField(upload_to='products')

    def __str__(self):
        return f'{self.product}'


class Review(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, SET('Deleted'))
    text = CharField(max_length=200)
    date = DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.product} {self.user}'


class Favourite(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, CASCADE)

    def __str__(self):
        return f'{self.product}'


class Cart(Model):
    product = ForeignKey(Product, CASCADE)
    user = ForeignKey(User, CASCADE)
    count = IntegerField(default=1)

    class Meta:
        ordering = ('count',)

    def __str__(self):
        return f'{self.product}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | ASL</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    {% block head %}{% endblock %}
</head>
<style>
    body {
        font-family: "Lato";
    }
</style>
{% block style %}{% endblock %}
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">About Smart Life</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarMenu"
                aria-controls="navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="navbarMenu"
             aria-labelledby="navbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="navbarLabel"><i class="fa-solid fa-list-ul"></i> Menu</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">
                            <i class="fa-solid fa-house mx-1"></i>Asosiy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:products' %}">
                            <i class="fa-solid fa-cart-plus mx-1"></i>Tovarlar
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fa-solid fa-user mx-1"></i>
                            {% if user.is_authenticated %}{{ user.get_full_name }}{% else %}Akkaunt{% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'main:settings' %}">
                                    <i class="fa-solid fa-gear mx-2"></i>
                                    Sozlamalar
                                </a></li>
                                <li><a class="dropdown-item" href="{% url 'main:cart' %}">
                                    <i class="fa-solid fa-cart-shopping mx-2"></i>
                                    Korzina
                                </a></li>
                                <li><a class="dropdown-item" href="{% url 'main:favourites' %}">
                                    <i class="fa-solid fa-heart mx-2"></i>
                                    Sevimlilar
                                </a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#logoutModel">
                                        <i class="fa-solid fa-right-from-bracket mx-2"></i> Chiqish
                                    </button>
                                </li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'main:login' %}">
                                    <i class="fa-solid fa-right-to-bracket mx-2"></i>
                                    Login
                                </a></li>
                                <li><a class="dropdown-item" href="{% url 'main:register' %}">
                                    <i class="fa-solid fa-user-plus mx-2"></i>
                                    Registratsiya
                                </a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                <form class="d-flex mt-3 mt-lg-0" role="search">
                    <input class="form-control me-2" type="search" placeholder="Qidirish" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</nav>
{% if msg %}
    <div class="text-center alert alert-{{ msg.0 }} d-flex align-items-center" role="alert">
        <div>{{ msg.1 }}</div>
    </div>
{% endif %}
<div class="container">
    {% block content %}{% endblock %}
</div>
<div class="modal fade" id="logoutModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Logout</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Siz rostan ham akkauntingizdan chiqib ketmoqchimisiz?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                <a href="{% url 'main:logout' %}" class="btn btn-danger">Chiqish</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <hr>
</div>
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item d-flex align-items-center">
                <i class="fa-solid fa-house" style="margin-left: 25px;"></i>
                <a href="{% url 'main:index' %}" class="nav-link px-2 text-muted">Asosiy</a>
            </li>
            <li class="nav-item d-flex align-items-center">
                <i class="fa-solid fa-cart-shopping" style="margin-left: 25px;"></i>
                <a href="{% url 'main:products' %}" class="nav-link px-2 text-muted">Tovarlar</a>
            </li>
            <li class="nav-item d-flex align-items-center">
                <i class="fa-brands fa-telegram" style="margin-left: 25px"></i>
                <a href="https://t.me/testlink/" target="_blank" class="nav-link px-2 text-muted">Telegram</a>
            </li>
        </ul>
        <p class="text-center text-muted">&copy; AboutSmartLife, 2022</p>
    </footer>
</div>
{% block script %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}About Smart Life{% endblock %}

{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-bold"><i class="fa-sharp fa-solid fa-bolt"></i> Hayotingizni biz bilan o'zgartiring</h1>
                <p class="lead text-muted">
                    About Smart Life &mdash; bu siz qidirgan sifatli, ishonchli, chiroyli va eng asosiysi, arzon
                    narxlarda bo'lgan
                    texnikalar do'koni.<br>Bizni tanlab siz o'zingizni pulingizni va vaqtinginzni tejagan bo'lasiz. Agar
                    hoxlasangiz,
                    tovarlarni pasdagi havolani bosib ko'rishingiz mumkin ;)
                </p>
                <p><a href="{% url 'main:products' %}" class="btn btn-success my-2">
                    <i class="fa-solid fa-cart-shopping mx-1"></i> Tovarlarni ko'rish</a></p>
            </div>
        </div>
    </section>
    <hr>
    <section class="categories p-5 m-auto">
        <h3 class="text-center">Kategoriyalar</h3>
        <div class="text-center">
            {% for category in categories %}
                <a href="{% url 'main:category-view' category.slug %}" class="btn btn-light shadow m-2"
                   style="width: 150px">
                    <img src="{{ category.icon.url }}" alt="{{ category.slug }}" width="40px" height="40px"
                         class="rounded">
                    <h6>{{ category.name }}</h6>
                </a>
            {% empty %}
                <h4 class="text-center">Afsuski, bizda hozir kategoriyalar yo'q :.(</h4>
            {% endfor %}
        </div>
    </section>
    <hr>
    {% if products %}
        <section class="cards p-5">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow h-100">
                            <a href="{% url 'main:view' product.slug %}" class="text-decoration-none">
                                <img src="{{ product.productimage_set.first.image.url }}"
                                     class="card-img-top" alt="{{ product.title }}" width="100%" height="100%">
                            </a>
                            <div class="card-body">
                                <a href="{% url 'main:view' product.slug %}" class="text-decoration-none">
                                    <h5 class="card-title text-dark">{{ product.title }}</h5>
                                </a>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Brand:</span>
                                    <span class="w-50">{{ product.brand }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Model:</span>
                                    <span class="w-50">{{ product.model }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Ishlab chiqarilgan:</span>
                                    <span class="w-50">{{ product.made }}</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Qolgan:</span>
                                    <span class="w-50">{{ product.count }} ta</span>
                                </div>
                                <hr style="margin-top: 5px; margin-bottom: 5px">
                                <div class="card-text d-flex w-100">
                                    <span class="w-50">Narxi:</span>
                                    <span class="w-50">{{ product.price }} so'm</span>
                                </div>
                            </div>
                            <div class="card-footer d-flex align-items-center">
                                <span class="text-muted">
                                    <i class="fa-solid fa-calendar-days mx-2"></i>
                                    {{ product.pub_date|timesince }}
                                </span>
                                <a class="text-muted text-decoration-none"
                                href="{% url 'main:category-view' product.category.slug %}">
                                    <i class="fa-solid fa-tags mx-2"></i>{{ product.category }}
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    {% else %}
        <h1 class="text-center my-5">Bizda hali tovarlar yo'q ...(</h1>
    {% endif %}
{% endblock %}